import type { Product } from "@/src/types/product";

export const products: Product[] = [
  {
    id: 1,
    name: "Hot Cherry Pepper and Sichuan Pickle",
    description:
      "Bold red cherry peppers mixed with tingling Sichuan pepper, slow cooked in mustard oil with garlic and ginger. One spoonful wakes up any meal.",
    price: 520,
    largePrice: 950,
    image: "/image.png",
    rating: 5,
    spiceLevel: "Extra Hot",
    type: "Mixed",
    inStock: true,
  },
  {
    id: 2,
    name: "Tangy Flax Seeds Achar",
    description:
      "Roasted flax seeds ground with green chilli, lemon and fresh coriander. Nutty, tangy and full of goodness. Goes perfectly with rice and dal.",
    price: 380,
    largePrice: 680,
    image: "/image.png",
    rating: 4,
    spiceLevel: "Medium",
    type: "Mixed",
    inStock: true,
  },
  {
    id: 3,
    name: "Mango Ginger and Garlic Pickle",
    description:
      "Raw mango pieces pickled with fresh ginger, whole garlic cloves and warming spices. Sweet, sour and deeply satisfying.",
    price: 420,
    largePrice: 750,
    image: "/image.png",
    rating: 5,
    spiceLevel: "Mild",
    type: "Mango",
    inStock: true,
  },
  {
    id: 4,
    name: "Bitter Gourd Pickle",
    description:
      "Thin sliced bitter gourd sun dried and slow cooked with mustard seeds, turmeric and chilli. An acquired taste that becomes a craving.",
    price: 380,
    largePrice: 680,
    image: "/image.png",
    rating: 4,
    spiceLevel: "Medium",
    type: "Mixed",
    inStock: true,
  },
  {
    id: 5,
    name: "Fenugreek Methi Pickle",
    description:
      "Whole fenugreek seeds tempered in hot mustard oil with dried chilli and asafoetida. Deeply aromatic and traditionally made the old way.",
    price: 360,
    largePrice: 650,
    image: "/image.png",
    rating: 4,
    spiceLevel: "Mild",
    type: "Mixed",
    inStock: true,
  },
  {
    id: 6,
    name: "Szechuan Sauce",
    description:
      "Freshly ground Nepali timur berries blended with garlic, ginger and red chilli into a thick sauce. The base of authentic Nepali cooking.",
    price: 480,
    largePrice: 880,
    image: "/image.png",
    rating: 5,
    spiceLevel: "Hot",
    type: "Mixed",
    inStock: true,
  },
  {
    id: 7,
    name: "Gundruk Bhatmas Pickle",
    description:
      "Fermented gundruk leaves mixed with roasted soybeans, fresh chilli and mustard oil. A true taste of the Nepali hills.",
    price: 400,
    largePrice: 720,
    image: "/image.png",
    rating: 4,
    spiceLevel: "Medium",
    type: "Mixed",
    inStock: true,
  },
  {
    id: 8,
    name: "Sweet Lapsi Pickle",
    description:
      "Nepali hog plum slow cooked with sugar, chilli and cardamom into a thick sweet and sour preserve. Addictive with every bite.",
    price: 390,
    largePrice: 700,
    image: "/image.png",
    rating: 5,
    spiceLevel: "Mild",
    type: "Mixed",
    inStock: true,
  },
  {
    id: 9,
    name: "Radish Pickle",
    description:
      "Crisp white radish pickled with mustard oil, turmeric and whole spices. Light, crunchy and the perfect side for any Nepali meal.",
    price: 360,
    largePrice: 650,
    image: "/image.png",
    rating: 4,
    spiceLevel: "Mild",
    type: "Mixed",
    inStock: true,
  },
  {
    id: 10,
    name: "Green Chilly Pickle",
    description:
      "Whole green chillies stuffed with a spiced mustard and fennel filling, preserved in oil. Fiery, flavourful and completely addictive.",
    price: 420,
    largePrice: 750,
    image: "/image.png",
    rating: 5,
    spiceLevel: "Hot",
    type: "Mixed",
    inStock: true,
  },
  {
    id: 11,
    name: "Dalla Lime Pickle",
    description:
      "Nepal's famous Dalle Khursani paired with fresh lime, salt and mustard oil. Incredibly hot and intensely sour. For the brave only.",
    price: 520,
    largePrice: 950,
    image: "/image.png",
    rating: 5,
    spiceLevel: "Extra Hot",
    type: "Mixed",
    inStock: true,
  },
  {
    id: 12,
    name: "Dalla in Brine",
    description:
      "Whole Dalle Khursani preserved in salt brine the traditional way. Clean heat, pure flavour and no added oil.",
    price: 480,
    largePrice: 880,
    image: "/image.png",
    rating: 4,
    spiceLevel: "Extra Hot",
    type: "Mixed",
    inStock: true,
  },
  {
    id: 13,
    name: "Dalla Pickle in Oil",
    description:
      "Dalle Khursani slow preserved in mustard oil with garlic and whole spices. Rich, fiery and deeply aromatic.",
    price: 500,
    largePrice: 920,
    image: "/image.png",
    rating: 5,
    spiceLevel: "Extra Hot",
    type: "Mixed",
    inStock: true,
  },
  {
    id: 14,
    name: "Dalla and Garlic Paste Pickle",
    description:
      "Dalle Khursani and fresh garlic ground into a thick paste with mustard oil and rock salt. Intense heat with deep garlic flavour.",
    price: 520,
    largePrice: 950,
    image: "/image.png",
    rating: 5,
    spiceLevel: "Extra Hot",
    type: "Mixed",
    inStock: true,
  },
  {
    id: 15,
    name: "Hot and Spicy Lapsi Pickle",
    description:
      "Nepali hog plum cooked with extra chilli, garlic and warming spices for those who want heat with their sweet and sour.",
    price: 420,
    largePrice: 750,
    image: "/image.png",
    rating: 4,
    spiceLevel: "Hot",
    type: "Mixed",
    inStock: true,
  },
  {
    id: 16,
    name: "Hot Cherry Pepper and Bamboo Pickle",
    description:
      "Tender bamboo shoots pickled with hot cherry peppers, mustard oil and fresh herbs. A mountain flavour unlike anything else.",
    price: 480,
    largePrice: 880,
    image: "/image.png",
    rating: 5,
    spiceLevel: "Hot",
    type: "Mixed",
    inStock: true,
  },
];
